### PR TITLE
Complete attribute based handling implementation 

### PR DESCRIPTION
**Pull request by xperiandri**
Including method dependency injection for effect handlers

### CODE REVIEW

**Comment by xperiandri** [comment]
Hide whitespace changes using the gear button to view only real code changes

**Comment by mrpmorris** [comment]
Before you continue...can you explain to me why having dependencies as parameters is better than having them injected via a constructor?

**Comment by xperiandri** [comment]
Because F# `module` is a static class

``` F#
module SignUpUser =

    type State =
        | Initial
        | SignigUp
        | SignUpError of Error : string

    type Feature () =
        inherit Feature<State> ()
        override __.GetName () = "SignUp"
        override __.GetInitialState () = Initial

    [<CLIMutable>]
    type Data =
        {
            [<Required>]
            FirstName : string
            [<Required>]
            LastName : string
            [<Required; JsonPropertyName("EmailAddress")>]
            Email : string
            [<Required>]
            Password : string
        }

    type Action =
        | SignUp of Data : Data * RedirectUri : Uri
        | ProcessSignUpResult of Result : Result<SignInUser.Data * Uri, string>

    [<ReducerMethod(StateType = typeof<State>)>]
    let reduce action =
        match action with
        | SignUp _ -> SignigUp
        | ProcessSignUpResult (Ok (_, _)) -> Initial
        | ProcessSignUpResult (Error message) -> SignUpError message

    let execute (httpClient : HttpClient) (signUpData : Data, redirectUri : Uri) =
        System.Console.WriteLine("Sign Up")
        async {
            try
                let body = JsonSerializer.Serialize(signUpData, Json.options)
                System.Console.WriteLine(body)
                let content = new StringContent(body, Encoding.UTF8, "application/json")
                let! response = httpClient.PostAsync (Api.Patient.signUp, content, Async.DefaultCancellationToken)
                let! message = response.Content.ReadAsStringAsync ()
                System.Console.WriteLine(message)
                //do! HttpClientJsonExtensions.PostJsonAsync(httpClient, Api.Security.loginUser, signInData)
                return Ok ({Email= signUpData.Email; Password= signUpData.Password; KeepSignedIn= true}, redirectUri)
            with e ->
                System.Console.WriteLine(e)
                return Error e.Message
        }

    [<EffectMethod>]
    let handle (httpClient : HttpClient) (dispatcher : IDispatcher)
               (authenticationState : IState<Authentication.State>) action =
        System.Console.WriteLine("Handled");
        async {
            let token =
                match authenticationState.Value with
                | Application (SignInApplication.State.SignedIn token) -> token
                | _ -> raise (UnauthorizedAccessException ())
            let! nextAction = async {
                match action with
                | SignUp (signUpData, redirectUri) ->
                    let! result = execute httpClient (signUpData, redirectUri)
                    return ProcessSignUpResult result :> obj
                | ProcessSignUpResult (Ok (signInData, redirectUri)) ->
                    return SignIn (token, signInData, redirectUri) :> obj
                | ProcessSignUpResult (Error _) ->
                    return () :> obj
            }
            System.Console.WriteLine("Dispatching {0}", nextAction);
            dispatcher.Dispatch nextAction
        }
        |> Async.StartAsTask :> Task
```

**Comment by xperiandri** [comment]
And in functional programming you usually pass dependencies via method parameters

**Comment by mrpmorris** [comment]
Surely there is an equivalent of a class with injected dependencies in which you can create multiple reducer methods?

**Comment by xperiandri** [comment]
I don't need that.
The idea is to have a single module and keep it in a single file.

**Comment by xperiandri** [comment]
Module that has state, actions, reducers and effects

**Comment by mrpmorris** [comment]
At the moment Fluxor will create delegates to avoid invoking methods via reflection.

I think your requirement to have all in a single file is a corner case and not worth the cost of slower running code.

**Comment by xperiandri** [comment]
Do you mean that invoking method passing parameters as `object[]` is slow?

**Comment by mrpmorris** [comment]
Yes, calling MethodInfo.Invoke is much slower. I just did a quick test to see how many times in 1 second I can invoke a method.

- 7023456: Reflection

**Comment by xperiandri** [comment]
Well, your concern is reasonable. However, this scenario is not performance-critical, in my opinion.
We can do optimization having 2 types of attributes:
1. Your implementation
2. My implementation
This way user can choose which one is good for his scenario

**Comment by mrpmorris** [comment]
I'm not happy to put this feature in. Isn't this sort of thing supposed to be achieved using function composition?

**Pull request closed without merging**
